In [1]:
import torch

torch.__version__

'2.9.1+cu128'

``` Scaler ```

* A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [2]:
scaler = torch.tensor(7)
print(scaler)

tensor(7)


In [3]:
# check the dimension of tensor
scaler.ndim

0

In [4]:
# Get the python nuber within a tensor

scaler.item()

7

``` Vector ```
* A vector is a single dimension tensor but can contain many numbers.

* As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

In [5]:
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [6]:
# check the number dimensions of vector

vector.ndim

1

In [7]:
# Check shape of vector

vector.shape

torch.Size([2])

```Matrix```

In [8]:

matrix = torch.tensor([[7,8],
                       [9,10]])

print(matrix)

tensor([[ 7,  8],
        [ 9, 10]])


In [9]:
# Check the dimensions of matrix
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

` Tensor `

In [11]:
# Tensor

tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Check of dimensions fo tensor
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

`` Tensor for random number ``
* we can do so using torch.rand() and passing in the size parameter

In [14]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2074, 0.3296, 0.8139, 0.1406],
         [0.1822, 0.8397, 0.4117, 0.7577],
         [0.3322, 0.8761, 0.6096, 0.0371]]),
 torch.float32)

In [15]:
## Create a random tensor of size

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.3356, 0.2760, 0.6136],
          [0.0700, 0.0495, 0.6335],
          [0.4093, 0.2000, 0.2419],
          ...,
          [0.0091, 0.8157, 0.2895],
          [0.7750, 0.8377, 0.9238],
          [0.6525, 0.7510, 0.1399]],
 
         [[0.2552, 0.3733, 0.3908],
          [0.3378, 0.9951, 0.8472],
          [0.2311, 0.4794, 0.4550],
          ...,
          [0.4320, 0.9919, 0.3773],
          [0.9693, 0.5625, 0.3304],
          [0.3920, 0.4944, 0.1405]],
 
         [[0.0689, 0.8634, 0.7975],
          [0.9072, 0.6762, 0.7806],
          [0.2377, 0.4706, 0.3713],
          ...,
          [0.9988, 0.6717, 0.5472],
          [0.8357, 0.8913, 0.7459],
          [0.1606, 0.4984, 0.6569]],
 
         ...,
 
         [[0.4534, 0.3300, 0.0846],
          [0.4599, 0.0610, 0.0144],
          [0.0447, 0.3141, 0.2479],
          ...,
          [0.6307, 0.5496, 0.1192],
          [0.5898, 0.7375, 0.5554],
          [0.5140, 0.1036, 0.5676]],
 
         [[0.8284, 0.8633, 0.3158],
          [0

* Create a tensor full of zeros with torch.zeros()

In [16]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

* Create a tensors of all ones except using torch.ones()

In [17]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

` Create a range and tensors like `

* you can use torch.arange(start, end step) to do so.

* start = start of range
* end = end of range
* step = how many steps in between each value

In [18]:
# use torch.range(), torch.arange()

zero_ten_deprecated = torch.range(0, 10)

zero_ten = torch.arange(start=0, end=10, step=1)
zero_ten

/tmp/ipykernel_54355/4138096473.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# can also a tensor of zeros simila to another tensor

ten_zeros = torch.zeros_like(input=zero_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

` Tensors Datatypes `
* Default datatype for tensor is float32


In [20]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16,
                               device=torch.device('cuda:0'))

float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

` Getting information from tensor `

* Three of the most common attribute you'll want to find out about tensors

* Shape - What shape is tensor ?
* dtype - what datatype are the elements within the tensor stored in?
* device - what device is the tensor stored on? (usually GPU or CPU)

In [22]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Devise tensor is stores on: {some_tensor.device}")

tensor([[0.0989, 0.1061, 0.3377, 0.8555],
        [0.7510, 0.3107, 0.6933, 0.8734],
        [0.2923, 0.9658, 0.4550, 0.7385]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Devise tensor is stores on: cpu


` Manipulating tensors (tensor operation) `
* Addition
* Substraction
* Multiplication
* Divison
* Matrix mu;tiplication

* Basics Operations

In [23]:
# Create a tensor of value and add a number on it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
# Substract and reassing
tensor = tensor -10

tensor

tensor([-9, -8, -7])

In [26]:
# add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [27]:
# can also use torch function
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [28]:
tensor

tensor([1, 2, 3])

In [29]:
# Element-wise multiplication

print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


` Matrix Multiplication `

* The inner dimensions must match:
*  (3, 2) @ (3, 2) won't work
*  (2, 3) @ (3, 2) will work
*  (3, 2) @ (2, 3) will work

In [30]:
# Create a tensor and perform element-wise multiplication and matrix multiplication

import torch
tensor = torch.tensor([1,2,3,4])
tensor.shape

torch.Size([4])

` Operation`	 `Calculation`	 `Code`
* Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	`tensor * tensor`
* Matrix multiplication	`[1*1 + 2*2 + 3*3] = [14]`	`tensor.matmul(tensor)`


In [31]:
# Element-wise matrix multiplication
tensor * tensor

tensor([ 1,  4,  9, 16])

In [32]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(30)

In [33]:
# can also user "@" for matrix multiplication
tensor @ tensor

tensor(30)

Matrix multiplication by hand

* The in-bulit torch.matmul() method is faster

In [34]:
%%time

value =0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.66 ms, sys: 28 μs, total: 1.69 ms
Wall time: 1.1 ms


tensor(30)

In [35]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 198 μs, sys: 0 ns, total: 198 μs
Wall time: 121 μs


tensor(30)

In [36]:
# Shape need to be in the right way

tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

`Transpose`

* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

In [37]:
# view tensor_a and tensor_b
print(tensor_a)
print(tensor_b)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [38]:
# vies tensor_a and tensor_b.T

print(tensor_a)
print(tensor_b.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [39]:
# The operation works when tensor_b is transposed

output = torch.matmul(tensor_a, tensor_b.T)

print(output)
print(output.shape)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
torch.Size([3, 3])


* You cal also use torch.mm() which is a short for torch.matmul().

In [40]:
output = torch.mm(tensor_a, tensor_b.T)

print(output)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [41]:
# Since the linear layer starts with a random weights

torch.manual_seed(42)

# Thise uses matrix multiplication
linear = torch.nn.Linear(in_features=2, out_features=6) # in_features = matches inner diension of input, out_featurs = describes outer value

x =  tensor_a

print("Innput shape: ", x.shape)
print("Output shape", output.shape)

Innput shape:  torch.Size([3, 2])
Output shape torch.Size([3, 3])


Finding the min, max, mean, sum

In [42]:
# Create a tensor

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
print(f"Mean {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum : 0
Maximum : 90
Mean 45.0
Sum: 450


In [44]:
# You can also do the same as above with torch meathod

torch.max(x), torch.min(x), torch.mean(x), torch.mean(x.type(torch.float32)) , torch.sum()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

` Positional min/max`

In [45]:
tensor = torch.arange(10, 100, 10)

print(f"Tensor: {tensor}")

print(f"Index where max value occurce: {tensor.argmax()}")
print(f"Index where min value occurse: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurce: 8
Index where min value occurse: 0


`Change tensor datatype`

In [46]:
# Create a tensor and check its datatype

tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [47]:
# Create a floate16 tensor

tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [48]:
# Create an int8 tensor

tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

` Reshaping, staking, squeezing and unsqueezing`

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

`Why do any of these`

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [49]:
# create a tensor

import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [50]:
# let's add an extra dimention with torch.reshape

# add extra dimention

x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

` Change th view with torch.view()`

In [51]:
# Change view (keeps same data as original but changes view)

z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Rememder though. changing the view of a tensor with torch.view() really only creates a new view of the same tensor

In [52]:
# Changing z changes x

z[:, 0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

if we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

In [53]:
# Stack tensors on the top of each other

x_stacked = torch.stack([x,x,x,x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

How about removing all single dimensions from a tensor ?

to do so you can use torch.squeeze() (i remember this as squeezing the tensor to only have dimension over 1)

In [54]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


And to do the reverse of  torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [55]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")



## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


you can also rearange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [57]:
# Create tensor with specific shape

x_original = torch.rand(size=(224,224,3))

#Premutes the original tensor to rearrange the axis order
x_premute = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_premute.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


`Indexing (Selecting data from tensors)`

dometimes you'll want to select specific data from tensors (for example only the first column or second row)

To do so, you can use indexing

In [58]:
#Create a tensor

import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

indexing values goes outer dimension -> inner dimension (check out the square brackets)

In [59]:
print(f"first square brackets:\n {x[0]}")
print(f"Second square brackets: {x[0][0]}")
print(f"Third square brackets: {x[0][0][0]}")

first square brackets:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square brackets: tensor([1, 2, 3])
Third square brackets: 1


You can also use : to specify all values in this dimension and then use a comma(,) to add another dimension.

In [74]:
x[:,0]
x[:,2] # third row
x[:,:,1] # accesing second column
x[:,:,0]  # accesing first column
x[0,0,:] # get index 0 of oth and 1st dimension and all values of 2nd dimesion

tensor([1, 2, 3])

`PyTorch tensors & Numpy`

THe two main method you'll want to use for Numpy to Pytorch(and back again) are:

* torch.from_numpy(ndarray) -Numpy array -> PyTorch tensor
* torch.Tensor.numpy() -PyTorch tensor ->Numpy array.

In [75]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
# Change the array keep the tensor

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

if you want to go from PyTorch tensor to NUmpy array, you can call tensor.numpy()

In [77]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

`Reproducibility (trying to take the random out of random)`

Example of reproducibility in PyTorch

In [78]:
import torch

#Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A: \n {random_tensor_A}")
print(f"Tensor B:\n {random_tensor_B}")

print(f"Does Tensor A equel Tensor B? (anywhere)")

random_tensor_A == random_tensor_B

Tensor A: 
 tensor([[0.8660, 0.2001, 0.7926, 0.1140],
        [0.6855, 0.0086, 0.3588, 0.9211],
        [0.8627, 0.8223, 0.5248, 0.5881]])
Tensor B:
 tensor([[0.2746, 0.3791, 0.2975, 0.6450],
        [0.0163, 0.9160, 0.5888, 0.8403],
        [0.4761, 0.7140, 0.4644, 0.6362]])
Does Tensor A equel Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

But what if you wanted to create two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

Let's try it out by creating some more flavoured random tensors.

In [79]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

#Have to reset the seed every time a new rand() is called
# without this, tensor_D would be different to tensor_c

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n {random_tensor_C}")
print(f"Tensor D:\n{random_tensor_D}")

random_tensor_C == random_tensor_D

Tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

`Running tensors on GPU (and making faster computation)`

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

` 1. Getting a GPU`

In [80]:
!nvidia-smi

Fri Jan  9 19:19:22 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650        Off |   00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8              2W /   50W |     120MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

`2. Getting PyTorch to run on the GPU`
Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the torch.cuda package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using torch.cuda.is_available().

In [81]:
# Check for GPU

import torch
torch.cuda.is_available()

True

In [82]:
# set devise type

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [83]:
# count number of devices

torch.cuda.device_count()

1

Let's tey creating a tensor and putting it on the GPU (if it's available)

In [84]:
#Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tesnso not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

`4. Moving tensors back to the CPU`

In [85]:
# If tensor is on GPU, cant transform it to Numpy

tensor_on_GPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [87]:
# Thise copies the tensor to CPU memory so its usable with CPUs

# Insted, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_GPU.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [88]:
# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU

tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')