In [2]:
import torch

torch.__version__

'2.9.1+cu128'

``` Scaler ```

* A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [7]:
scaler = torch.tensor(7)
print(scaler)

tensor(7)


In [8]:
# check the dimension of tensor
scaler.ndim

0

In [9]:
# Get the python nuber within a tensor

scaler.item()

7

``` Vector ```
* A vector is a single dimension tensor but can contain many numbers.

* As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

In [11]:
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [12]:
# check the number dimensions of vector

vector.ndim

1

In [13]:
# Check shape of vector

vector.shape

torch.Size([2])

```Matrix```

In [14]:

matrix = torch.tensor([[7,8],
                       [9,10]])

print(matrix)

tensor([[ 7,  8],
        [ 9, 10]])


In [15]:
# Check the dimensions of matrix
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

` Tensor `

In [18]:
# Tensor

tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
# Check of dimensions fo tensor
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

`` Tensor for random number ``
* we can do so using torch.rand() and passing in the size parameter

In [21]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.5131, 0.6960, 0.6133, 0.9032],
         [0.9339, 0.4153, 0.9012, 0.7116],
         [0.4792, 0.7018, 0.9774, 0.7037]]),
 torch.float32)

In [23]:
## Create a random tensor of size

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor, random_image_size_tensor.ndim

(tensor([[[0.7469, 0.8810, 0.0473],
          [0.0445, 0.0514, 0.7700],
          [0.2189, 0.8390, 0.1162],
          ...,
          [0.0198, 0.9910, 0.4860],
          [0.6790, 0.1665, 0.5706],
          [0.2612, 0.8114, 0.8673]],
 
         [[0.8897, 0.3777, 0.0213],
          [0.5471, 0.0228, 0.5683],
          [0.9520, 0.7892, 0.9180],
          ...,
          [0.5656, 0.7491, 0.0305],
          [0.8748, 0.0934, 0.8388],
          [0.4199, 0.1082, 0.8758]],
 
         [[0.6829, 0.8139, 0.6774],
          [0.5705, 0.5992, 0.4692],
          [0.1020, 0.4944, 0.5097],
          ...,
          [0.9074, 0.7248, 0.8959],
          [0.6844, 0.0061, 0.0871],
          [0.0267, 0.0719, 0.4663]],
 
         ...,
 
         [[0.0523, 0.6001, 0.5272],
          [0.5553, 0.7721, 0.9098],
          [0.4230, 0.3524, 0.3300],
          ...,
          [0.2360, 0.9918, 0.0016],
          [0.6123, 0.3434, 0.9796],
          [0.2655, 0.5544, 0.8291]],
 
         [[0.6934, 0.4150, 0.3643],
          [0

* Create a tensor full of zeros with torch.zeros()

In [24]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

* Create a tensors of all ones except using torch.ones()

In [25]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

` Create a range and tensors like `

* you can use torch.arange(start, end step) to do so.

* start = start of range
* end = end of range
* step = how many steps in between each value

In [27]:
# use torch.range(), torch.arange()

zero_ten_deprecated = torch.range(0, 10)

zero_ten = torch.arange(start=0, end=10, step=1)
zero_ten

/tmp/ipykernel_30646/4138096473.py:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# can also a tensor of zeros simila to another tensor

ten_zeros = torch.zeros_like(input=zero_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

` Tensors Datatypes `
* Default datatype for tensor is float32


In [29]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [31]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16,
                               device=torch.device('cuda:0'))

float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

` Getting information from tensor `

* Three of the most common attribute you'll want to find out about tensors

* Shape - What shape is tensor ?
* dtype - what datatype are the elements within the tensor stored in?
* device - what device is the tensor stored on? (usually GPU or CPU)

In [32]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Devise tensor is stores on: {some_tensor.device}")

tensor([[0.7749, 0.8298, 0.4309, 0.6964],
        [0.7398, 0.5533, 0.1053, 0.1153],
        [0.3111, 0.9128, 0.5028, 0.0079]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Devise tensor is stores on: cpu


` Manipulating tensors (tensor operation) `
* Addition
* Substraction
* Multiplication
* Divison
* Matrix mu;tiplication

* Basics Operations

In [33]:
# Create a tensor of value and add a number on it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Substract and reassing
tensor = tensor -10

tensor

tensor([-9, -8, -7])

In [37]:
# add and reassign
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [38]:
# can also use torch function
torch.multiply(tensor, 10)

tensor([110, 120, 130])

In [39]:
tensor

tensor([11, 12, 13])

In [41]:
# Element-wise multiplication

print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([11, 12, 13]) * tensor([11, 12, 13])
Equals: tensor([121, 144, 169])


` Matrix Multiplication `

* The inner dimensions must match:
*  (3, 2) @ (3, 2) won't work
*  (2, 3) @ (3, 2) will work
*  (3, 2) @ (2, 3) will work

In [42]:
# Create a tensor and perform element-wise multiplication and matrix multiplication

import torch
tensor = torch.tensor([1,2,3,4])
tensor.shape

torch.Size([4])

` Operation`	 `Calculation`	 `Code`
* Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	`tensor * tensor`
* Matrix multiplication	`[1*1 + 2*2 + 3*3] = [14]`	`tensor.matmul(tensor)`


In [43]:
# Element-wise matrix multiplication
tensor * tensor

tensor([ 1,  4,  9, 16])

In [45]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(30)

In [46]:
# can also user "@" for matrix multiplication
tensor @ tensor

tensor(30)

Matrix multiplication by hand

* The in-bulit torch.matmul() method is faster

In [48]:
%%time

value =0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.18 ms, sys: 8.64 ms, total: 9.83 ms
Wall time: 12.3 ms


tensor(30)

In [49]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 182 μs, sys: 61 μs, total: 243 μs
Wall time: 176 μs


tensor(30)

In [50]:
# Shape need to be in the right way

tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

`Transpose`

* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* tensor.T - where tensor is the desired tensor to transpose.

In [51]:
# view tensor_a and tensor_b
print(tensor_a)
print(tensor_b)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [53]:
# vies tensor_a and tensor_b.T

print(tensor_a)
print(tensor_b.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [54]:
# The operation works when tensor_b is transposed

output = torch.matmul(tensor_a, tensor_b.T)

print(output)
print(output.shape)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
torch.Size([3, 3])


* You cal also use torch.mm() which is a short for torch.matmul().

In [55]:
output = torch.mm(tensor_a, tensor_b.T)

print(output)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
